### ISSUE TITLE
Scraping other information besides profiles (company profiles, jobs)

### ISSUE THREAD

**Issue by c0bra** [linkedtales/scrapedin#25]
Is there any interest in adding this sort of scraping? It would require changing the API as it's pretty much centered around profiles only. I have a potential use-case for it, though.

**Comment by leonardiwagner** [comment]
Yes, sure! let's do an experiment about that, just tell what are you thinking about :smile_cat:

**Comment by leonardiwagner** [comment]
Closing issue due to lack of feedback

**Comment by a10kiloham** [comment]
fwiw would be useful to have company data too

**Comment by Netgator** [comment]
Yea sorry I would find that helpful too - actually I was working towards that the last time I worked on this and then realized that there would be a number of changes needed...

**Comment by leonardiwagner** [comment]
if you guys create a "companyScraperTemplate.js" like [profileScraperTemplate.js](https://github.com/linkedtales/scrapedin/blob/master/src/profileScraperTemplate.js) I can work on changing the rest of API

**Comment by gigaBITE397** [comment]
Hey,

As mentioned by @a10kiloham. I do want to work on Company data scrapper.

When I submit Company URL instead of the user Profile URL, the scrapper should go to the Company page then click on **see all employee** and then it will see all employee data. 

1. It should click on each employee and fetch data from the profile as we already do (one by one operation). 
2. Then, it should click on view more and continue its operation 

Scrapper should repeat it's operation.

As you mentioned above, I tried Creating companyScrapperTemplate for Step 1 and created click functionality and see more functionality in those relative files.

But it does not seem to be working

> if you guys create a "companyScraperTemplate.js" like [profileScraperTemplate.js](https://github.com/linkedtales/scrapedin/blob/master/src/profileScraperTemplate.js) I can work on changing the rest of API
