### ISSUE TITLE
lt-line-clamp__more only click for the first match

### ISSUE THREAD

**Issue by wagaman** [linkedtales/scrapedin#26]
correct me if I am wrong 

const clickAll = async(page) => {
  for(let i = 0; i < seeMoreButtons.length; i ++){
    const button = seeMoreButtons[i]

    if (button.selector) {
      const elem = await page.$(button.selector)
      if (elem) {

if a selector matches more than one result, then we need to loop to click.
I observed, for example, only one see_more is being clicked and the rest is ignored.

**Comment by wagaman** [comment]
and also, we should loop selectors first and then selector in [const seeMoreButtons]
because clicking on load more cancels the "see more" action.

**Comment by leonardiwagner** [comment]
Hi @wagaman , thanks for reporting this bug! Yes, it was clicking more than once, because I was matching `.lt-line-clamp__more`  twice:[ lines 4 and 10](https://github.com/linkedtales/scrapedin/blob/81c41e35a605545d5749e509c6547fe112b2d826/src/seeMoreButtons.js)

I fixed that and I published at `v1.0.8` please update your version!

**Comment by leonardiwagner** [comment]
About the question about the code, `seeMoreButtons` should contain aways **individual** elements, that's why we shouldn't look for more than one result.

> and also, we should loop selectors first and then selector in [const seeMoreButtons]
**because clicking on load more cancels the "see more" action**.

I tested with a few profiles and it seems to be working, maybe it was the same bug. Please report again if it's happening with a profile link, thank you @wagaman !

**Comment by leonardiwagner** [comment]
@wagaman I just released `v1.0.9` that should fix this problem, please update your version.

Please update this issue if the problem still persists.
