### ISSUE TITLE
Position descriptions get truncated

### ISSUE THREAD

**Issue by jessica-yang** [linkedtales/scrapedin#31]
The `description` for each `position` gets truncated

Example:
```
positions: [
  {
    ...
    description: "my very long descr... "
    ...
  }
];
```

Is it possible to fix this or is it due to limitations on LinkedIn's APIs?

**Comment by leonardiwagner** [comment]
@jessica-yang it's a bug indeed. There's no restriction, we just need to click on "show more" button to see the whole description.

This is the file responsible for doing that: [seeMoreButtons.js](https://github.com/linkedtales/scrapedin/blob/master/src/seeMoreButtons.js) , probably some css class has changed.

**Comment by leonardiwagner** [comment]
It has changed, now [`positions`](https://github.com/linkedtales/scrapedin/blob/master/src/seeMoreButtons.js#L5) should be `.pv-position-entity .lt-line-clamp__less` I guess

you can try changing that code in your local `/node_modules/scrapedin` and feel free to open a PR if that works @jessica-yang 

I won't do something right now because seems this whole "see more" mechanic can be changed (maybe `.lt-line-clamp__less` work for all "see more" elements now), and require a lot of time to test as well and I'm not able to do that now since I'm traveling.

**Comment by jessica-yang** [comment]
Thanks for getting back to me so quickly @leonardiwagner! I'll try this out in my `node_modules` and see if it works.

Could you expand a bit more on this?:
> seems this whole "see more" mechanic can be changed (maybe .lt-line-clamp__less work for all "see more" elements now)

**Comment by leonardiwagner** [comment]
@jessica-yang just and improvement, because at [`seeMoreButtons.js`](https://github.com/linkedtales/scrapedin/blob/master/src/seeMoreButtons.js) we have each CSS selector for each LinkedIn section.

If we can have a more generic way of handling it, clicking on only one CSS selector to expand all "see more" info that would be better :smile:

**Comment by jessica-yang** [comment]
Ah. Thanks for the explanation! That makes sense. Changing what you suggested in `node_modules/scrapedin/src/seeMoreButtons.js` to

```{ id: "positions", selector: ".pv-position-entity .lt-line-clamp__less" }```

Didn't solve the issue. That's okay though and I understand there's a lot to test and you're traveling as well. Maybe I'll open a PR if I figure it out. Thanks 👍

**Comment by leonardiwagner** [comment]
I just released the `v1.0.9` version which should solve this problem, you can update your version. 

Please re-open this issue if it's still not working, thank you.

**Comment by jessica-yang** [comment]
Thank you so much for doing this @leonardiwagner! Will check it out and verify

**Comment by jessica-yang** [comment]
Hey @leonardiwagner I don't think I can reopen the issue, but I finally got around to trying it out and I still face the same issue. Here's an example snippet of how the response looks like:
```
{
  "title": "Torrey Commerce",
  "location": "San Diego",
  "description": "• Collaborated in team of software engineers to develop software solutions for e-commerce platforms\n• Created and maintained PHP scripts to implement and fix features for multi-channel retailers\n• Developed APIs following RESTful API design and utilized PHP and SQL for both developers and clients to efficiently manage 1000+ product transactions\n\n…\nsee more"
}
```

You can see the `\nseemore` there at the end of the description. Just to confirm, I'm on version `1.0.10`. If it's helpful, this is my profile that I'm trying to scrape: https://www.linkedin.com/in/jessicayang15/ Thanks for your help and all you've done on this project!

**Comment by leonardiwagner** [comment]
@jessica-yang Okay, it seems that issue about being truncated was solved because it's gathering the whole information, however, there's "dirty data" at the end, is that right?

So, there are two things to consider:

1. LinkedIn has changed "See more" to "see more", [that's why the library isn't removing that](https://github.com/linkedtales/scrapedin/blob/master/src/profile/cleanProfileData.js#L47), I'm going to update that in the next release, it's alright :+1: 

2. Besides the 'see more' it comes along `\n\n…\` portion, I recommend you to filter these fields by yourself instead of relying on the library cleanup.
The idea of this library is to only deliver the raw data, and that `\n\n\` is part of it. I'm not sure but I believe even their API retrieves data in this way, so I'd recommend doing a cleanup about your needs after consuming what scrapedin retrieves, even removing the 'see more' as well :+1:

**Comment by jessica-yang** [comment]
Ah you're completely right! I mistakenly thought it wasn't returning the whole thing because of that, but it actually is returning all the text. If that's the case, that's all I need and can do the cleanup myself like you said. Thanks so much! 🙂
