### ISSUE TITLE
I want to scrape company info, can i use it as my tool?

### ISSUE THREAD

**Issue by clown-0726** [linkedtales/scrapedin#41]

**Comment by leonardiwagner** [comment]
Hi @clown-0726 , sure, any additional data you want to scrap just place in the template file: https://github.com/linkedtales/scrapedin/blob/master/src/profileScraperTemplate.js

related to #25

**Comment by gigaBITE397** [comment]
Hey,

As mentioned in [#25](https://github.com/linkedtales/scrapedin/issues/25) . I do want to work on Company data scrapper.

When I submit Company URL instead of the user Profile URL, the scrapper should go to the Company page then click on see all employees and then it will see all employee data.

It should click on each employee and fetch data from the profile as we already do (one by one operation).
Then, it should click on view more and continue its operation
Scrapper should repeat it's operation.

As you mentioned above, I tried Creating companyScrapperTemplate for Step 1 and created click functionality and see more functionality in those relative files.

But it does not seem to be working

**Comment by leonardiwagner** [comment]
Hi @gigaBITE397 , where's the code that you tried to achieve that? please show me and I can help

**Comment by leonardiwagner** [comment]
closing due to lack of feedback
